### ISSUE TITLE
Fatal NetLogo error when opening another model after using r:setPlotDevice and JavaGD

### ISSUE THREAD

**Issue by DOSull** [NetLogo/R-Extension#12]
My r extension seems to be installed fine. I can open models that use it successfully and they run OK. They can load R libraries (such as spatstat, for example) and the link to R is fine. However, after I make an R plot via r:setPlotDevice and the JavaGD library, then go to open another model, I get a fatal NetLogo crash, with the error report show below.

This seems to happen even with the demonstration model for making boxplots if I close the plot device with the dev-off button. Presumably some kind of 'clean up' issue? I'm runing on Ubuntu 18.0.4, NetLogo 6.0.4, R 3.4.4.

```
java.lang.NoClassDefFoundError: org/nlogo/extension/r/Entry$LibC
 at org.nlogo.extension.r.Entry.validateRHome(Entry.java:247)
 at org.nlogo.extension.r.Entry.runOnce(Entry.java:121)
 at org.nlogo.workspace.ExtensionManager.initializedClassManager(ExtensionManager.scala:202)
 at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:165)
 at scala.Option.getOrElse(Option.scala:121)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:163)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:71)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:69)
 at scala.collection.immutable.List.foreach(List.scala:389)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:69)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:35)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:42)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:50)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:202)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:64)
 at org.nlogo.window.Events$LoadEndEvent.beHandledBy(Events.java:462)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5(ReconfigureWorkspaceUI.scala:40)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5$adapted(ReconfigureWorkspaceUI.scala:40)
 at scala.collection.immutable.List.foreach(List.scala:389)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.loadHelper(ReconfigureWorkspaceUI.scala:40)
 at org.nlogo.window.ReconfigureWorkspaceUI$.apply(ReconfigureWorkspaceUI.scala:19)
 at org.nlogo.app.FileManager.org$nlogo$app$FileManager$$runLoad(FileManager.scala:302)
 at org.nlogo.app.FileManager$$anon$3.run(FileManager.scala:363)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1(ModalProgressTask.scala:26)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1$adapted(ModalProgressTask.scala:24)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$display$1(ModalProgressTask.scala:18)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1671)
 at java.awt.Component.setVisible(Component.java:1623)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.display(ModalProgressTask.scala:20)
 at org.nlogo.swing.ModalProgressTask$.onUIThread(ModalProgressTask.scala:24)
 at org.nlogo.app.FileManager.openFromModel(FileManager.scala:367)
 at org.nlogo.app.FileManager.$anonfun$openFromURI$1(FileManager.scala:280)
 at org.nlogo.app.FileManager.$anonfun$openFromURI$1$adapted(FileManager.scala:280)
 at scala.Option.foreach(Option.scala:257)
 at org.nlogo.app.FileManager.openFromURI(FileManager.scala:280)
 at org.nlogo.app.FileManager.openFromPath(FileManager.scala:276)
 at org.nlogo.app.OpenRecentFileAction.open(RecentFilesMenu.scala:67)
 at org.nlogo.app.OpenRecentFileAction.actionPerformed(RecentFilesMenu.scala:61)
 at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
 at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
 at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
 at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
 at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
 at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
 at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
 at java.awt.Component.processMouseEvent(Component.java:6539)
 at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
 at java.awt.Component.processEvent(Component.java:6304)
 at java.awt.Container.processEvent(Container.java:2239)
 at java.awt.Component.dispatchEventImpl(Component.java:4889)
 at java.awt.Container.dispatchEventImpl(Container.java:2297)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
 at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
 at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
 at java.awt.Container.dispatchEventImpl(Container.java:2283)
 at java.awt.Window.dispatchEventImpl(Window.java:2746)
 at java.awt.Component.dispatchEvent(Component.java:4711)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
 at java.awt.EventQueue$4.run(EventQueue.java:733)
 at java.awt.EventQueue$4.run(EventQueue.java:731)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.0.4
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_172 (Oracle Corporation; 1.8.0_172-b11)
operating system: Linux 4.15.0-38-generic (amd64 processor)
Scala version 2.12.4
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: 3.1-local-average-using-R

01:27:43.589 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
01:27:43.582 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
01:27:43.582 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
01:27:43.582 CompileMoreSourceEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
01:27:43.582 RemoveJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
01:27:43.582 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
01:27:43.582 CompileMoreSourceEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
01:27:43.582 RemoveJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
01:27:43.581 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
01:27:43.581 CompileMoreSourceEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
```

**Comment by DOSull** [comment]
Hi - still seeing this problem two years later(!) with Netlogo 6.1.1 and R 3.6.4. 

Everything works fine, but when I go to open another model that also uses the R extension I get the fatal error and can't do anything with that model. I can open other models that don't use the R extension OK. 

But any time later in the Netlogo session that I go to open a model that uses the R extension I get the Internal Error with a very similar detailed message diving deep into the Java error trace. It starts with `java.lang.NoClassDefFoundError: org/nlogo/extension/r/Entry$LibC` as before.

Other models are fine, but it's still a pain!
