### ISSUE TITLE
R Extension - JavaError

### ISSUE THREAD

**Issue by jmfhdat19** [NetLogo/R-Extension#20]
Had some troubles installing the R Extension, but finally made it with moving user.properties from AppData/Roaming/NetLogo/6.1/extensions/r to ..NetLogo/6.1./r, BUT... 
now I'm getting this error message, would be happy to get some support.... 

ERROR: 

NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.nio.file.InvalidPathException: Illegal char <:> at index 2: 'C:/Program Files/R/R-3.6.2'
 at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
 at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
 at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
 at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
 at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
 at java.nio.file.Paths.get(Paths.java:84)
 at org.nlogo.extension.r.Configuration.<init>(Configuration.java:103)
 at org.nlogo.extension.r.Configuration.fromRExtensionProperties(Configuration.java:94)
 at org.nlogo.extension.r.Entry.runOnce(Entry.java:120)
 at org.nlogo.workspace.ExtensionManager.initializedClassManager(ExtensionManager.scala:196)
 at org.nlogo.workspace.ExtensionManager.$anonfun$importExtension$8(ExtensionManager.scala:159)
 at scala.Option.getOrElse(Option.scala:138)
 at org.nlogo.workspace.ExtensionManager.importExtension(ExtensionManager.scala:157)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1(StructureParser.scala:74)
 at org.nlogo.parse.StructureParser$.$anonfun$parsingWithExtensions$1$adapted(StructureParser.scala:68)
 at scala.collection.immutable.List.foreach(List.scala:392)
 at org.nlogo.parse.StructureParser$.parsingWithExtensions(StructureParser.scala:68)
 at org.nlogo.parse.StructureParser$.parseSources(StructureParser.scala:33)
 at org.nlogo.parse.NetLogoParser.basicParse(NetLogoParser.scala:17)
 at org.nlogo.parse.NetLogoParser.basicParse$(NetLogoParser.scala:15)
 at org.nlogo.parse.FrontEnd$.basicParse(FrontEnd.scala:10)
 at org.nlogo.parse.FrontEndMain.frontEnd(FrontEnd.scala:26)
 at org.nlogo.parse.FrontEndMain.frontEnd$(FrontEnd.scala:25)
 at org.nlogo.parse.FrontEnd$.frontEnd(FrontEnd.scala:10)
 at org.nlogo.compile.CompilerMain$.compile(CompilerMain.scala:43)
 at org.nlogo.compile.Compiler.compileProgram(Compiler.scala:54)
 at org.nlogo.window.CompilerManager.compileProcedures(CompilerManager.scala:209)
 at org.nlogo.window.CompilerManager.compileAll(CompilerManager.scala:173)
 at org.nlogo.window.CompilerManager.handle(CompilerManager.scala:64)
 at org.nlogo.window.Events$LoadEndEvent.beHandledBy(Events.java:462)
 at org.nlogo.window.Event.doRaise(Event.java:198)
 at org.nlogo.window.Event.raise(Event.java:122)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5(ReconfigureWorkspaceUI.scala:41)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.$anonfun$loadHelper$5$adapted(ReconfigureWorkspaceUI.scala:41)
 at scala.collection.immutable.List.foreach(List.scala:392)
 at org.nlogo.window.ReconfigureWorkspaceUI$Loader.loadHelper(ReconfigureWorkspaceUI.scala:41)
 at org.nlogo.window.ReconfigureWorkspaceUI$.apply(ReconfigureWorkspaceUI.scala:19)
 at org.nlogo.app.FileManager.org$nlogo$app$FileManager$$runLoad(FileManager.scala:303)
 at org.nlogo.app.FileManager$$anon$2.run(FileManager.scala:365)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1(ModalProgressTask.scala:26)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$onUIThread$1$adapted(ModalProgressTask.scala:24)
 at org.nlogo.swing.ModalProgressTask$.$anonfun$display$1(ModalProgressTask.scala:18)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
 at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
 at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
 at java.awt.Dialog.show(Dialog.java:1084)
 at java.awt.Component.show(Component.java:1671)
 at java.awt.Component.setVisible(Component.java:1623)
 at java.awt.Window.setVisible(Window.java:1014)
 at java.awt.Dialog.setVisible(Dialog.java:1005)
 at org.nlogo.swing.ModalProgressTask$.display(ModalProgressTask.scala:20)
 at org.nlogo.swing.ModalProgressTask$.onUIThread(ModalProgressTask.scala:24)
 at org.nlogo.app.FileManager.openFromModel(FileManager.scala:369)
 at org.nlogo.app.FileManager.$anonfun$openFromURI$1(FileManager.scala:280)
 at org.nlogo.app.FileManager.$anonfun$openFromURI$1$adapted(FileManager.scala:280)
 at scala.Option.foreach(Option.scala:274)
 at org.nlogo.app.FileManager.openFromURI(FileManager.scala:280)
 at org.nlogo.app.FileManager.openFromPath(FileManager.scala:276)
 at org.nlogo.app.App.$anonfun$open$1(App.scala:875)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at org.nlogo.app.App.dispatchThreadOrBust(App.scala:1144)
 at org.nlogo.app.App.open(App.scala:875)
 at org.nlogo.app.App.loadDefaultModel(App.scala:513)
 at org.nlogo.app.App.org$nlogo$app$App$$finishStartup(App.scala:452)
 at org.nlogo.app.App$.$anonfun$mainWithAppHandler$1(App.scala:161)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

NetLogo 6.1.1
main: org.nlogo.app.AppFrame
thread: AWT-EventQueue-0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: boxplot-example

11:35:41.762 RemoveAllJobsEvent (org.nlogo.window.CompilerManager) AWT-EventQueue-0
11:35:41.753 LoadEndEvent (org.nlogo.window.ReconfigureWorkspaceUI$Loader (java.lang.Object)) AWT-EventQueue-0
11:35:41.752 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
11:35:41.752 CompileMoreSourceEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
11:35:41.752 RemoveJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
11:35:41.751 WidgetAddedEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
11:35:41.751 CompileMoreSourceEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
11:35:41.751 RemoveJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
11:35:41.751 WidgetAddedEvent (org.nlogo.widget.NoteWidget) AWT-EventQueue-0
11:35:41.749 WidgetAddedEvent (org.nlogo.widget.NoteWidget) AWT-EventQueue-0

**Comment by LaCuneta** [comment]
Thanks for your interest in the R extension, and sorry you ran into these setup problems.

Just to make sure we're on the same page, you mention you're having trouble "installing" the R extension, do you mean just getting it configured to run or are you downloading it from somewhere to install manually?  It comes bundled with NetLogo 6.1.1, so just the configuration steps are necessary once you have 6.1.1 installed.  Also, you are running NetLogo 6.1.1 app as normal, not from a command line script or otherwise, correct?

If you are using the bundled 6.1.1 version normally, then the next step is to take a look at your `user.properties` file.  Can you post the exact contents of that file here?  Then could you post the corresponding output of the commands from the [instructions on determining those values](https://ccl.northwestern.edu/netlogo/docs/r.html#determining-rhome-and-jrihomepaths)?

**Comment by jmfhdat19** [comment]
I'm using the bundled 6.1.1 version, so I'm having problems with configuring and I'm using the app :-)
first point was that the user.properties file couldn't be found, so I moved it as described above;
now NetLogo finds the user.properties file, but has some problems with the Path of r.home.
The content of that file is:
`r.home='C:/Program Files/R/R-3.6.2' ` -> Problem with illegal character :
`#r.home=C:/PROGRA~1/R/R-36~1.2 ` -> Error Nr. 5 for home
`jri.home.paths='C:/Users/<MYUSER>/Documents/R/win-library/3.6/rJava/jri'`

Values according to the output of the commands in the instructions :-) 
Thank you very much for your help!!

**Comment by LaCuneta** [comment]
Thanks for the extra information!  I don't have a Windows machine to test on at the moment, but what happens if you drop the single quotes from both settings (as below)?  I'm also not quite sure what `Err Nr. 5 for home` means, can you elaborate?

```
r.home=C:/PROGRA~1/R/R-36~1.2
jri.home.paths=C:/Users/<MYUSER>/Documents/R/win-library/3.6/rJava/jri
```

**Comment by jmfhdat19** [comment]
Dropping the single quotes yields to this error message:
"Error setting R_HOME(#05)" - that's what I meant with "Error Nr. for home"... sorry for not being that precise...

**Comment by LaCuneta** [comment]
Gotcha, thank you, that's helpful!  Did you get through [the Windows-specific setup instructions here](https://ccl.northwestern.edu/netlogo/docs/r.html#windows-specific-installation-steps) to set your system `PATH` with the R bin folder?  I think that error *might* be related to not finding files from that folder.

**Comment by jmfhdat19** [comment]
Got the right path here too... is there some known issue that the colon is a "illegal character" as statet in the error message above?

**Comment by LaCuneta** [comment]
On Windows the `:` character is very common in file paths, and we did test the extension on Windows and have had other users report success with it, so I would be very surprised if that on its own was causing issues.  I'll try to get ahold of a Windows 10 computer to test on later today and come up with more things to try.  Thanks for your patience!

Edit to ask:  Are you using 64-bit or 32-bit of NetLogo/R?

**Comment by jmfhdat19** [comment]
Thank you very much! I also checked the encoding of the file, seems all to be fine.. really curious what it could be.... :-)

**Comment by LaCuneta** [comment]
I got on a Windows 10 machine to test, but unfortunately everything worked for me.  I was able to come up with a couple more things to try.

To start, here is the `user.properties` file I used (same as what I'd posted before, really):

```
r.home=C:/PROGRA~1/R/R-36~1.2
jri.home.paths=C:/Users/<MY_USERNAME>/Documents/R/win-library/3.6/rJava/jri
```

And here is what I added to my `PATH` environment variable: `C:\Program Files\R\R-3.6.2\bin\x64`

Then, to try to reproduce your errors:

- Used single quotes around `r.home` value, got the same colon path error you did, so I do not think this is the root cause - we just can't use single quotes around paths with the R extension settings.
- I changed the `r.home` value to a bad path, got error #1, so not related.  I changed the `jri.home.paths` value to a bad path, got error #2, so not related.
- Changed the `PATH` value to a bad path and did not get your error #5.

So then I took a closer look at the code that generates the error #5 and come up with a couple of ideas:

- First, make sure the Visual C++ 2013 runtime packages are installed, you can grab them from Microsoft:  https://www.microsoft.com/en-us/download/details.aspx?id=40784
- If that doesn't help, try setting the `R_HOME` environment variable manually.  In your environment variables settings, instead of **Edit...** to change `PATH`, do `New...` and add `R_HOME` with a value of `C:\PROGRA~1\R\R-36~1.2`.  No single or double quotes around it, but this time using backslashes instead of forward slashes.  You can probably comment out the `r.home` value in your `user.properties` to avoid confusion, too, but it shouldn't be necessary.

And one other thing I thought of, you mentioned you had moved the `user.properties` from the `AppData\Roaming\NetLogo\6.1\extensions` folder.  Do you know if you installed the R extension using the NetLogo extensions manager, maybe using NetLogo 6.1.0?  That might have an impact if so.

I hope one of those ideas works, but let me know if not and I'll continue checking through possibilities.

**Comment by jmfhdat19** [comment]
Thank you very much for your effort!

Finally made it that, the R Extension is loading: 
Steps I tried: 
- Reinstalling Visual C++ 2013 runtime package  - still got an Error
- Manually seeting path value, but this time with `New...` instead of `Edit`  - this lead me to  a different error, next step: 
- Changing from open open JDK to JDE : its loading! :-) 

So far so good, now I can open the example models but getting two new errors: 
- Error: package or namespace load failed for 'stats' in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Program Files/R/R-3.6.2/library/stats/libs/x64/stats.dll':
  LoadLibrary failure:  Das angegebene Modul wurde nicht gefunden. (=in English: Modul was not found)
- During startup - Warning message:
package 'stats' in options("defaultPackages") was not found 

With these error messages I can't use eval/get/... 
So far, thank you very much for patience!

**Comment by jmfhdat19** [comment]
Guess the problem is the "stats" package :-) So I tried the following things:
- Load R Extension in Netlogo
- Open interactive shell: `r:interactiveshell` and typed: `.libPaths()`

Output is as expected - the two librarys defined in user.properties
The stats package is in C:/Program Files/R/R-3.6.2/library, the folder ist there, the .dll is there. 
So I don't why the Extension couldn't load "stats".... searching again :-)

**Comment by jmfhdat19** [comment]
Finally - it works! 
According to Issue #5 I added `C:\Program Files\R\R-3.6.2\bin\x64` and `C:\Program Files\R\R-3.6.2` to my Path and now everything works fine.. 
Thank you!! :-)

**Comment by LaCuneta** [comment]
Glad to hear!  Thank you for updating with what was necessary to get things working, it'll be helpful for the next person who has trouble.

**Comment by edmizac** [comment]
> Thank you very much for your effort!
> 
> Finally made it that, the R Extension is loading: Steps I tried:
> 
> * Reinstalling Visual C++ 2013 runtime package  - still got an Error
> * Manually seeting path value, but this time with `New...` instead of `Edit`  - this lead me to  a different error, next step:
> * Changing from open open JDK to JDE : its loading! :-)
> 
> So far so good, now I can open the example models but getting two new errors:
> 
> * Error: package or namespace load failed for 'stats' in inDL(x, as.logical(local), as.logical(now), ...):
>   unable to load shared object 'C:/Program Files/R/R-3.6.2/library/stats/libs/x64/stats.dll':
>   LoadLibrary failure:  Das angegebene Modul wurde nicht gefunden. (=in English: Modul was not found)
> * During startup - Warning message:
>   package 'stats' in options("defaultPackages") was not found
> 
> With these error messages I can't use eval/get/... So far, thank you very much for patience!

Hi [jmfhdat19](https://github.com/jmfhdat19), 

Would you provide more details on the part of changing JDK to JDE? How did you do it, exactly? Thanks!
